### ISSUE TITLE
Document how to add comments in an IDL file for fastrtpsgen

### ISSUE THREAD

**Issue by realdealneil** [eProsima/Fast-RTPS-docs#101]
I have been looking for somewhere that documents how to add comments to IDL files used by fastrtpsgen.  This would be helpful to know about.  I ended up trying regular C++ comments, and that seemed to work, but it should be documented somewhere.  If it is, please point me to that documentation.  Also, it would be nice to have more examples of idl files in the documentation (ones that use enums and structs within structs, things like that).  Thanks!

**Comment by EduPonz** [comment]
Hi @realdealneil ,

Sorry for the late response. As you say, comments similar to C++ style are supported in IDL file. We are right now expanding out Fast DDS-Gen documentation in #165 and will most definitely include your suggestion. In the mean time, you can take a look at the [Interface Definition Language v4.2 standard](https://www.omg.org/spec/IDL/4.2/PDF), which is what Fast DDS-Gen implements. Specifically, section 7.2.2 describes how to comment and IDL.

Thanks for picking that up a putting the time to make the suggestion.

**Comment by EduPonz** [comment]
Hi @realdealneil ,

We have effectively merger #165 now, adding a section about IDL comments. You can see it [here](https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/dataTypes/dataTypes.html#idl-4-2-comments).

Please do tell us if you consider it to be thorough enough, and if so, please close this issue.

**Comment by realdealneil** [comment]
Thanks, looks good!  Closing.

**Comment by realdealneil** [comment]
Closed
