### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by wutianze** [eProsima/Fast-RTPS-docs#157]
In Fast DDS/Getting Started/1.3. Writing a simple publisher and subscriber application
Follow the steps and compile error:
HelloWorldPublisher.cpp:41:5: error: ‘Topic’ does not name a type
   41 |     Topic* topic_;

I check the include files and couldn't find Topic definition. Please check this issue and help.
Thank you!

**Comment by MiguelCompany** [comment]
Please bear in mind that the latest documentation refers to the latest release (v2.0.0). If you are using a previous release, like 1.10.0, use that version of the docs (i.e. https://fast-dds.docs.eprosima.com/en/v1.10.0)

**Comment by EduPonz** [comment]
Was the answer satisfactory? If so, please mark the issue as closed.
